pretrained_model_path: "/content/drive/MyDrive/gen_image_workspace/diffusion_video_models/Tune-A-Video/checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/gligen"

train_data:
  video_path: "data/man-skiing.mp4"
  prompt: "a man is skiing"
  n_sample_frames: 24
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 2


validation_data:
  prompts:
    - "Teddy bear skiing on the silver curved spoon"
    - "Teddy bear with his girlfriend wearing a couple-look sweaters, warm tone"

  video_length: 24
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 1000
validation_steps: 100
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True

train_gligen_boxes: [[0.4, 0.2, 0.7, 0.8]]
train_gligen_phrases: ["man"]

val_gligen_boxes: 
  - [[0.4, 0.2, 0.7, 0.8]]
  - [[0.4, 0.2, 0.7, 0.8], [0.5, 0.6, 0.8, 0.9]]
val_gligen_phrases:  
  - ["Teddy"]
  - ["Teddy","his girlfirend"]


